# Generated by Django 4.1.3 on 2022-11-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_added',
            new_name='date_added',
        ),
    ]
